version: "3.5"

services:
  bcc-node:
    image: tbco/bcc-node
    environment:
      NETWORK:
    volumes:
      - node-${NETWORK}-db:/data
      - node-ipc:/ipc
      - node-config:/nix/store
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  bcc-wallet:
    image: tbco/bcc-wallet:2021.9.29
    volumes:
      - wallet-${NETWORK}-db:/wallet-db
      - node-ipc:/ipc
    ports:
      - 8090:8090
    entrypoint: []
    command: bash -c "
        ([[ $$NETWORK == \"mainnet\" ]] && $$CMD --mainnet) ||
        ($$CMD --testnet /config/${NETWORK}/genesis-cole.json)
      "
    environment:
      CMD: "bcc-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
      NETWORK:
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

volumes:
  node-mainnet-db:
  node-testnet-db:
  node-aurum-purple-db:
  wallet-mainnet-db:
  wallet-testnet-db:
  wallet-aurum-purple-db:
  node-ipc:
  node-config:
