{
  extras = hackage:
    {
      packages = {
        "OddWord" = (((hackage.OddWord)."1.0.2.0").revisions).default;
        "command" = (((hackage.command)."0.1.1").revisions).default;
        "hspec" = (((hackage.hspec)."2.8.2").revisions).default;
        "hspec-core" = (((hackage.hspec-core)."2.8.2").revisions).default;
        "hspec-discover" = (((hackage.hspec-discover)."2.8.2").revisions).default;
        "cryptonite" = (((hackage.cryptonite)."0.27").revisions).default;
        "Cabal" = (((hackage.Cabal)."3.4.0.0").revisions).default;
        "containers" = (((hackage.containers)."0.6.4.1").revisions).default;
        "dns" = (((hackage.dns)."3.0.4").revisions).default;
        "network" = (((hackage.network)."3.1.2.1").revisions).default;
        "ral" = (((hackage.ral)."0.1").revisions).default;
        "recursion-schemes" = (((hackage.recursion-schemes)."5.1.3").revisions).default;
        "text" = (((hackage.text)."1.2.4.0").revisions).default;
        "Win32" = (((hackage.Win32)."2.6.2.0").revisions).default;
        "async-timer" = (((hackage.async-timer)."0.2.0.0").revisions).default;
        "beam-core" = (((hackage.beam-core)."0.9.1.0").revisions).default;
        "beam-migrate" = (((hackage.beam-migrate)."0.5.1.0").revisions).default;
        "beam-sqlite" = (((hackage.beam-sqlite)."0.5.1.0").revisions).default;
        "canonical-json" = (((hackage.canonical-json)."0.6.0.0").revisions).default;
        "composition-prelude" = (((hackage.composition-prelude)."3.0.0.2").revisions).default;
        "constraints-extras" = (((hackage.constraints-extras)."0.3.1.0").revisions).default;
        "ip" = (((hackage.ip)."1.5.1").revisions).default;
        "gray-code" = (((hackage.gray-code)."0.3.1").revisions).default;
        "lazy-search" = (((hackage.lazy-search)."0.1.2.1").revisions).default;
        "lazysmallcheck" = (((hackage.lazysmallcheck)."0.6").revisions).default;
        "libsystemd-journal" = (((hackage.libsystemd-journal)."1.4.4").revisions).default;
        "markov-chain-usage-model" = (((hackage.markov-chain-usage-model)."0.0.0").revisions).default;
        "micro-recursion-schemes" = (((hackage.micro-recursion-schemes)."5.0.2.2").revisions).default;
        "monoidal-containers" = (((hackage.monoidal-containers)."0.6.0.1").revisions).default;
        "moo" = (((hackage.moo)."1.2").revisions).default;
        "nothunks" = (((hackage.nothunks)."0.1.2").revisions).default;
        "partial-order" = (((hackage.partial-order)."0.2.0.0").revisions).default;
        "quickcheck-state-machine" = (((hackage.quickcheck-state-machine)."0.7.0").revisions).default;
        "regex-posix-clib" = (((hackage.regex-posix-clib)."2.7").revisions).default;
        "row-types" = (((hackage.row-types)."1.0.1.0").revisions).default;
        "servant-subscriber" = (((hackage.servant-subscriber)."0.7.0.0").revisions).default;
        "dom-lt" = (((hackage.dom-lt)."0.2.2.1").revisions).default;
        "servant-websockets" = (((hackage.servant-websockets)."2.0.0").revisions).default;
        "size-based" = (((hackage.size-based)."0.1.2.0").revisions).default;
        "statistics-linreg" = (((hackage.statistics-linreg)."0.3").revisions).default;
        "streaming-binary" = (((hackage.streaming-binary)."0.2.2.0").revisions).default;
        "time-interval" = (((hackage.time-interval)."0.1.1").revisions).default;
        "time-out" = (((hackage.time-out)."0.2").revisions).default;
        "transformers-except" = (((hackage.transformers-except)."0.1.1").revisions).default;
        "Unique" = (((hackage.Unique)."0.4.7.6").revisions).default;
        "binary" = (((hackage.binary)."0.8.8.0").revisions).default;
        "parsec" = (((hackage.parsec)."3.1.14.0").revisions).default;
        bcc-wallet-core = ./bcc-wallet-core.nix;
        bcc-wallet-core-integration = ./bcc-wallet-core-integration.nix;
        bcc-wallet-cli = ./bcc-wallet-cli.nix;
        bcc-wallet-launcher = ./bcc-wallet-launcher.nix;
        bcc-numeric = ./bcc-numeric.nix;
        text-class = ./text-class.nix;
        bcc-wallet-test-utils = ./bcc-wallet-test-utils.nix;
        bcc-wallet = ./bcc-wallet.nix;
        strict-non-empty-containers = ./strict-non-empty-containers.nix;
        bcc-addresses-cli = ./bcc-addresses-cli.nix;
        bcc-addresses = ./bcc-addresses.nix;
        optparse-applicative-fork = ./optparse-applicative-fork.nix;
        base-deriving-via = ./base-deriving-via.nix;
        bcc-binary = ./bcc-binary.nix;
        bcc-binary-test = ./bcc-binary-test.nix;
        bcc-crypto-class = ./bcc-crypto-class.nix;
        bcc-crypto-praos = ./bcc-crypto-praos.nix;
        bcc-crypto-tests = ./bcc-crypto-tests.nix;
        orphans-deriving-via = ./orphans-deriving-via.nix;
        bcc-slotting = ./bcc-slotting.nix;
        strict-containers = ./strict-containers.nix;
        measures = ./measures.nix;
        bcc-crypto = ./bcc-crypto.nix;
        bcc-ledger-aurum = ./bcc-ledger-aurum.nix;
        bcc-ledger-aurum-test = ./bcc-ledger-aurum-test.nix;
        cole-spec-chain = ./cole-spec-chain.nix;
        bcc-crypto-wrapper = ./bcc-crypto-wrapper.nix;
        bcc-crypto-test = ./bcc-crypto-test.nix;
        cole-spec-ledger = ./cole-spec-ledger.nix;
        bcc-ledger-cole = ./bcc-ledger-cole.nix;
        bcc-ledger-cole-test = ./bcc-ledger-cole-test.nix;
        bcc-ledger-core = ./bcc-ledger-core.nix;
        small-steps = ./small-steps.nix;
        small-steps-test = ./small-steps-test.nix;
        sophie-spec-non-integral = ./sophie-spec-non-integral.nix;
        sophie-spec-ledger = ./sophie-spec-ledger.nix;
        sophie-spec-ledger-test = ./sophie-spec-ledger-test.nix;
        bcc-ledger-sophie-ma = ./bcc-ledger-sophie-ma.nix;
        bcc-ledger-sophie-ma-test = ./bcc-ledger-sophie-ma-test.nix;
        bcc-api = ./bcc-api.nix;
        bcc-cli = ./bcc-cli.nix;
        bcc-config = ./bcc-config.nix;
        bcc-node = ./bcc-node.nix;
        bcc-prelude = ./bcc-prelude.nix;
        bcc-prelude-test = ./bcc-prelude-test.nix;
        bcc-sl-x509 = ./bcc-sl-x509.nix;
        flat = ./flat.nix;
        shepards = ./shepards.nix;
        hedgehog-extras = ./hedgehog-extras.nix;
        contra-tracer = ./contra-tracer.nix;
        tbco-monitoring = ./tbco-monitoring.nix;
        lobemo-backend-aggregation = ./lobemo-backend-aggregation.nix;
        lobemo-backend-ekg = ./lobemo-backend-ekg.nix;
        lobemo-backend-monitoring = ./lobemo-backend-monitoring.nix;
        lobemo-backend-trace-forwarder = ./lobemo-backend-trace-forwarder.nix;
        lobemo-scribe-systemd = ./lobemo-scribe-systemd.nix;
        tracer-transformers = ./tracer-transformers.nix;
        purescript-bridge = ./purescript-bridge.nix;
        io-classes = ./io-classes.nix;
        io-sim = ./io-sim.nix;
        monoidal-synchronisation = ./monoidal-synchronisation.nix;
        network-mux = ./network-mux.nix;
        shardagnostic-consensus = ./shardagnostic-consensus.nix;
        shardagnostic-consensus-test = ./shardagnostic-consensus-test.nix;
        shardagnostic-consensus-cole = ./shardagnostic-consensus-cole.nix;
        shardagnostic-consensus-colespec = ./shardagnostic-consensus-colespec.nix;
        shardagnostic-consensus-cole-test = ./shardagnostic-consensus-cole-test.nix;
        shardagnostic-consensus-sophie = ./shardagnostic-consensus-sophie.nix;
        shardagnostic-consensus-sophie-test = ./shardagnostic-consensus-sophie-test.nix;
        shardagnostic-consensus-bcc = ./shardagnostic-consensus-bcc.nix;
        shardagnostic-consensus-bcc-test = ./shardagnostic-consensus-bcc-test.nix;
        shardagnostic-network = ./shardagnostic-network.nix;
        shardagnostic-network-framework = ./shardagnostic-network-framework.nix;
        shardagnostic-network-testing = ./shardagnostic-network-testing.nix;
        typed-protocols = ./typed-protocols.nix;
        typed-protocols-examples = ./typed-protocols-examples.nix;
        bcc-client = ./bcc-client.nix;
        ntp-client = ./ntp-client.nix;
        shardagnostic-consensus-mock = ./shardagnostic-consensus-mock.nix;
        freer-extras = ./freer-extras.nix;
        playground-common = ./playground-common.nix;
        zerepoch-chain-index = ./zerepoch-chain-index.nix;
        zerepoch-contract = ./zerepoch-contract.nix;
        zerepoch-core = ./zerepoch-core.nix;
        zerepoch-ledger = ./zerepoch-ledger.nix;
        zerepoch-ledger-api = ./zerepoch-ledger-api.nix;
        zerepoch-pab = ./zerepoch-pab.nix;
        zerepoch-tx = ./zerepoch-tx.nix;
        zerepoch-tx-plugin = ./zerepoch-tx-plugin.nix;
        zerepoch-use-cases = ./zerepoch-use-cases.nix;
        zerepoch-ghc-stub = ./zerepoch-ghc-stub.nix;
        prettyprinter-configurable = ./prettyprinter-configurable.nix;
        quickcheck-dynamic = ./quickcheck-dynamic.nix;
        word-array = ./word-array.nix;
        servant-purescript = ./servant-purescript.nix;
        Win32-network = ./Win32-network.nix;
        };
      compiler.version = "8.10.5";
      compiler.nix-name = "ghc8105";
      };
  resolver = "lts-18.5";
  modules = [
    ({ lib, ... }:
      {
        packages = {
          "bcc-crypto-praos" = {
            flags = { "external-libsodium-vrf" = lib.mkOverride 900 false; };
            };
          "cryptonite" = {
            flags = { "support_rdrand" = lib.mkOverride 900 false; };
            };
          "zip" = { flags = { "disable-bzip2" = lib.mkOverride 900 true; }; };
          };
        })
    { packages = { "$locals" = { ghcOptions = [ "-fwrite-ide-info" ]; }; }; }
    ({ lib, ... }:
      { planned = lib.mkOverride 900 true; })
    ];
  compiler = "ghc-8.10.5";
  }